### ISSUE TITLE
Quine in Rust

### ISSUE THREAD

**Issue by MadhuNimmo** [MadhuNimmo/QuinesInAllLangs#1]
Write an acceptable quine (a program that prints itself ) in Rust

**Comment by Ranadheer-senani** [comment]
I want to add a quine in Rust.

**Comment by Ranadheer-senani** [comment]
Hello, can you help me with how to merge my code into this repository? I'm done modifying the code in the forked repo.

**Comment by MadhuNimmo** [comment]
Please drop a pull request

**Comment by Ranadheer-senani** [comment]
Thank you, that was my first successful contribution.

**Comment by MadhuNimmo** [comment]
@Ranadheer-senani congratulations
