### ISSUE TITLE
Quine in C++

### ISSUE THREAD

**Issue by MadhuNimmo** [MadhuNimmo/QuinesInAllLangs#18]
Write an acceptable quine (a program that prints itself ) in C++

**Comment by yoursmanjunad** [comment]
Hey, I got solved this issue. Can I make a pull request to make a change for this C++ file? This is the code #include <iostream>
#include <string>

int main() {
    std::string s = "std::string s = %c%s%1$c; printf(s.c_str(), 34, s.c_str());";
    printf(s.c_str(), 34, s.c_str());
    return 0;
}

**Comment by dhananjay0610** [comment]
Hi, @MadhuNimmo ,can you please assign this to me.

**Comment by MadhuNimmo** [comment]
@yoursmanjunad  please make a pull request

**Comment by MadhuNimmo** [comment]
@dhananjay0610 please find another language @yoursmanjunad is working on this.

**Comment by Nayem73** [comment]
is the issue still open? can I be of any help?

**Comment by HimanshuKhatarkar** [comment]
Hi @MadhuNimmo  I can See that this issue is still Open. and I have the solution so can you Please assign this to me?
