### ISSUE TITLE
Quine in Perl

### ISSUE THREAD

**Issue by MadhuNimmo** [MadhuNimmo/QuinesInAllLangs#19]
Write an acceptable quine (a program that prints itself ) in Perl

**Comment by GustavoHiguera** [comment]
Hello! I am working on this C:

**Comment by GustavoHiguera** [comment]
#22 Here is the code! Thanks for the opportunity to contribute!

**Comment by dhananjay0610** [comment]
Can you please assign this to me

**Comment by diegoborbadev** [comment]
This issue shouldn't be closed? It has already have been solved in https://github.com/MadhuNimmo/QuinesInAllLangs/pull/22
