### ISSUE TITLE
Quine in Pascal

### ISSUE THREAD

**Issue by MadhuNimmo** [MadhuNimmo/QuinesInAllLangs#2]
Write an acceptable quine (a program that prints itself ) in Pascal

**Comment by iamhardikat11** [comment]
I would Love to take up this Issue.

**Comment by Narayan1670** [comment]
Hey @MadhuNimmo can I be assigned this issue?

**Comment by kanishk88** [comment]
hey I have sent you a pull request do check.

**Comment by sachinnandan** [comment]
Hey I would like to work on this. Can I get started

**Comment by SWAMIADITYA** [comment]
hey can you assign me this issue ?

**Comment by MadhuNimmo** [comment]
Hi, @SWAMIADITYA this is closed already. Please find another issue.
