### ISSUE TITLE
Quine in Lisp

### ISSUE THREAD

**Issue by MadhuNimmo** [MadhuNimmo/QuinesInAllLangs#20]
Write an acceptable quine (a program that prints itself ) in Lisp

**Comment by tymnec** [comment]
Possible Solution: ((lambda (x) (format t x x)) "(lambda (x) (format t x x)~%~S)~%")

**Comment by tymnec** [comment]
Possible Solution: file attached
[file.txt](https://github.com/MadhuNimmo/QuinesInAllLangs/files/11131357/file.txt)

**Comment by diegoborbadev** [comment]
I've created a *Pull Request* for this: https://github.com/MadhuNimmo/QuinesInAllLangs/pull/27
