### ISSUE TITLE
Quine in Haskell

### ISSUE THREAD

**Issue by MadhuNimmo** [MadhuNimmo/QuinesInAllLangs#21]
Write an acceptable quine (a program that prints itself ) in Haskell

**Comment by yoursmanjunad** [comment]
Hey, I got the code functioning on this; could you please do a pull request?

**Comment by yoursmanjunad** [comment]
Hey, I've worked on this and it runs successfully as well. Can I pull a request to make changes? This is the code --- main = putStrLn $ s ++ show s where s = "main = putStrLn $ s ++ show s where s = "

**Comment by mohanNaryana** [comment]
hey, this is what i got
main :: IO ()
main = putStrLn $ let sourceCode = "main :: IO ()\nmain = putStrLn $ let sourceCode = " ++ show sourceCode ++ " in sourceCode" in sourceCode

**Comment by HimanshuKhatarkar** [comment]
main = putStrLn $ let s = "main = putStrLn $ let s = " ++ show s ++ " in s" in s 

This code uses the show function to generate a string representation of the code itself and then prints that string using putStrLn.

I can Help with other problems(issues) as well please allow me to help you with this.
